spring.application.name=garajes-y-empleados
server.port=9000
#**** OPCIONAL ****
#Añade un subdominio al entrypoint por ejemplo http://localhost:8080/api/v1
server.servlet.context-path=/api/v1

#Especificamos el dialecto de Hibernate para comunicarse con la base de datos que vamos a utilizar
#Hibernate es un framework de mapeo objeto-relacional para java. Es parte del ecosistema JPA
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect
#spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MySQL8Dialect
#Cómo Hibernate maneja la creación y actualización de las tablas en la BD
# update: Actualiza la estructura de la BD sin borrar datos. Se utiliza en desarrollo
# create: Elimina y crea las tablas en cada inicio de la aplicación
# create-drop: Igual que create pero elimina las tablas al detener la aplicación
# validate: Comprueba que la estructura de la BD coincide con las entidades, pero no modifica
# none: No hace cambios. Se utiliza en producción
spring.jpa.hibernate.ddl-auto=update
#Configuración de la conexión con la BD PostgreSQL
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=mysecretpassword
#Configuración de la conexión con la BD MySQL
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.datasource.url=jdbc:mysql://localhost:3306/garajesyempleados?useSSL=false
#spring.datasource.username=root
#spring.datasource.password=1234